name: Create PR
run-name: Creating PR from ${{ github.ref_name }}

on:
  push:

jobs:
  create-pr:
    if: github.event_name == 'workflow_call'
        || inputs.head != github.event.repository.default_branch
    runs-on: ubuntu-latest
    permissions:
       pull-requests: write
       contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          version.txt
        sparse-checkout-cone-mode: false
    - name: Create PR from ${{ github.ref_name }}
      uses: lime-actions/pr-sync@latest
      with:
        version-from: 'version-file'
